name: List all default GitHub variables

on:
    push:
        branches: ["main"]
    
    pull_request:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
  ubuntu-environment-variables:
    runs-on: ubuntu-latest
    steps:
      - name: List environment variables
        run: printenv
  windows-environment-variables:
    runs-on: windows-latest
    steps:
      - name: List environment variables
        run: printenv
  